### ISSUE TITLE
Compass doesn't work when device orientation is changed

### ISSUE THREAD

**Issue by vishalseshagiri** [rahulhaque/compass-react-native#5]

**Comment by rahulhaque** [comment]
Screen orientation is now locked to portrait mode.

**Comment by vishalseshagiri** [comment]
converting x to -y and y to -z did it for my orientation, amazing work btw @rahulhaque

**Comment by rahulhaque** [comment]
Thank you and appreciate the gesture. Feel free to share the work. Closing the issue. Reopen if needed.
