### ISSUE TITLE
help, !!!! how can i integrate qibla direction here??

### ISSUE THREAD

**Issue by zahidahmed024** [rahulhaque/compass-react-native#6]

**Comment by asotjrs** [comment]
i think what he exactly means is how to make the pointer stick to a specific place on earth no matter how you change your location , any tips on how to do that ?

**Comment by rahulhaque** [comment]
@asotjrs as he mentioned qibla which varies based on location, and this compass is based on magnetometer which makes no attempt to get user location, his requirement is quite irrelevant in this context. If you want to fix a direction, third party API may help to find the degree of qibla and plot on this.

**Comment by asotjrs** [comment]
Thank you for your response
